export const chains = {
  sepolia :"sepolia",
  baseSepolia : "baseSepolia",
  avalancheFuji : "avalancheFuji",
  arcTestnet : "arcTestnet",
  hyperliquidEvmTestnet : "hyperliquidEvmTestnet",
  seiTestnet : "seiTestnet",
  sonicTestnet : "sonicTestnet",
  worldchainSepolia : "worldchainSepolia",
  // monadTestnet : "monadTestnet"
}

export const bridge = {
    Algorand : "Algorand",
    Algorand_Testnet : "Algorand_Testnet",
    Aptos : "Aptos",
    Aptos_Testnet : "Aptos_Testnet",
    Arc_Testnet : "Arc_Testnet",
    Arbitrum : "Arbitrum",
    Arbitrum_Sepolia : "Arbitrum_Sepolia",
    Avalanche : "Avalanche",
    Avalanche_Fuji : "Avalanche_Fuji",
    Base : "Base",
    Base_Sepolia : "Base_Sepolia",
    Celo : "Celo",
    Celo_Alfajores_Testnet : "Celo_Alfajores_Testnet",
    Codex : "Codex",
    Codex_Testnet : "Codex_Testnet",
    Ethereum : "Ethereum",
    Ethereum_Sepolia : "Ethereum_Sepolia",
    Hedera : "Hedera",
    Hedera_Testnet : "Hedera_Testnet",
    HyperEVM : "HyperEVM",
    HyperEVM_Testnet : "HyperEVM_Testnet",
    Ink : "Ink",
    Ink_Testnet : "Ink_Testnet",
    Linea : "Linea",
    Linea_Sepolia : "Linea_Sepolia",
    Monad : "Monad",
    Monad_Testnet : "Monad_Testnet",
    NEAR : "NEAR",
    NEAR_Testnet : "NEAR_Testnet",
    Noble : "Noble",
    Noble_Testnet : "Noble_Testnet",
    Optimism : "Optimism",
    Optimism_Sepolia : "Optimism_Sepolia",
    Polkadot_Asset_Hub : "Polkadot_Asset_Hub",
    Polkadot_Westmint : "Polkadot_Westmint",
    Plume : "Plume",
    Plume_Testnet : "Plume_Testnet",
    Polygon : "Polygon",
    Polygon_Amoy_Testnet : "Polygon_Amoy_Testnet",
    Sei : "Sei",
    Sei_Testnet : "Sei_Testnet",
    Solana : "Solana",
    Solana_Devnet : "Solana_Devnet",
    Sonic : "Sonic",
    Sonic_Testnet : "Sonic_Testnet",
    Stellar : "Stellar",
    Stellar_Testnet : "Stellar_Testnet",
    Sui : "Sui",
    Sui_Testnet : "Sui_Testnet",
    Unichain : "Unichain",
    Unichain_Sepolia : "Unichain_Sepolia",
    World_Chain : "World_Chain",
    World_Chain_Sepolia : "World_Chain_Sepolia",
    XDC : "XDC",
    XDC_Apothem : "XDC_Apothem",
    ZKSync_Era : "ZKSync_Era",
    ZKSync_Sepolia : "ZKSync_Sepolia"
}
